name: Deploy Production
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.SSH_DEPLOY_KEY }}
    - run: |
        ssh -o StrictHostKeyChecking=no root@159.203.108.203 << EOF
          cd /home/george/animeawards-mkii
          git pull
          systemctl restart animeawards
        EOF
