name: Deploy Production
on:
  push:
    branches:
    - master
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v1
    - uses: webfactory/ssh-agent@v0.1.1
      with:
        ssh-private-key: ${{ secrets.AWARDS_WEB_SSH_KEY }}
    - run: |
        ssh -o StrictHostKeyChecking=no awards-web@134.209.0.181 << EOF
          cd /home/awards-web/awards-web
          git fetch --all
          git reset --hard origin/master
          sudo systemctl restart awards-web.service
        EOF
